# Layout
# On push:
#  - Lint
#  - Coverage (test only 'en' on Linux)
# On PR to master (push, plus:)
#  - Full test (all OSes)

name: Quick-Build
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        python-version: [3.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]
      - name: Lint
        run: flake8 --count --show-source --statistics
      - name: Type Check
        if: matrix.python-version > 3
        run: |
          pip install mypy
          mypy . --ignore-missing-imports
      - name: Unit Test
        run: pytest -v -s gtts/
        env:
          TEST_LANGS: en

# name: Pull Request
# on:
#   pull_request:
#     branches:
#     - master

# jobs:
#   build:

#     runs-on: ${{ matrix.os }}
#     strategy:
#       max-parallel: 8
#       matrix:
#         # python-version: [2.7, 3.5, 3.6, 3.7]
#         python-version: [3.7]
#         # os: [ubuntu-latest, macOS-latest, windows-latest]
#         os: [ubuntu-latest]

#     steps:
#       - uses: actions/checkout@v1
#       - uses: actions/setup-python@v1
#         with:
#           python-version: ${{ matrix.python-version }}
#       - name: Install
#         run: |
#           python -m pip install --upgrade pip
#           pip install -e .[tests]
#       - name: Lint
#         run: flake8 --count --show-source --statistics
#       - name: Type Check
#         if: matrix.python-version > 3
#         run: |
#           pip install mypy
#           mypy . --ignore-missing-imports
#       - name: Unit Test
#         run: pytest -v -s gtts/
#         env:
#           TEST_LANGS: en