name: full-test
on:
  pull_request:
    branches:
    - master

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]
      - name: Lint
        run: flake8 --count --show-source --statistics
      - name: Type Check
        if: matrix.python-version > 3
        run: |
          pip install mypy
          mypy . --ignore-missing-imports
      - name: Unit Test (en)
        run: pytest -v -s gtts/
        env:
          TEST_LANGS: en
      - name: Unit Test (all languages) 
        # Only test all languages once
        if: matrix.python-version == 3.7 && matrix.os == 'ubuntu-latest'
        run: pytest -v -s gtts/tests/test_tts.py
        env:
          TEST_LANGS: all