# Layout
# On push:
#  - Lint
#  - Coverage (test only 'en' on Linux)
# On PR to master (push, plus:)
#  - Full test (all OSes)

name: CI
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # python-version: [2.7, 3.5, 3.6, 3.7]
        python-version: [3.7]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
    - name: Lint
      run: flake8 --count --show-source --statistics
    - name: Test
      if: matrix.python-version >= 3
      run: |
        pip install mypy && mypy . --ignore-missing-imports
      env:
        TEST_LANGS: 'en'
        


# name: Deploy
# on:
#   pull_request:
#     branches:
#     - master