name: Push
on: [push]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only the 'latest' of each
        python-version: ['2.x', '3.x']

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tests]

      - name: Lint
        run: flake8 --count --show-source --statistics

      - name: Type Check
        if: matrix.python-version == '3.x'
        run: |
          pip install mypy
          mypy . --ignore-missing-imports

      - name: Unit Tests
        run: pytest -v -s gtts/
        env:
          TEST_LANGS: en