name: Update Languages

on:
  schedule:
    # At 01:00 AM, on Monday
    - cron: 0 1 * * 1
  workflow_dispatch:
  
  # Temp, to test on PR:
  pull_request:
    branches:
      - main

env:
  CURR_LANG_FILE_PATH: ${{github.workspace}}/gtts/langs.py
  TEMP_LANG_FILE_PATH: ${{github.workspace}}/scripts/langs_temp.py

jobs:
  gen_langs:
    runs-on: ubuntu-latest
    name: Generate Languages

    # TODO: permissions to create branch, commit, PR

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install gTTS
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run gen_langs.py
        # Generate languages from the source
        run: |
          python scripts/gen_langs.py ${TEMP_LANG_FILE_PATH}
      - name: Run check_langs.py
        # Compare generated languages with current ones
        run: |
          python scripts/check_langs.py
        # Replace gtts langs.py with langs_temps if must_commit
        # Create new branch/PR with any changes if must_commit
